### ISSUE TITLE
【一般】管理门户》镜像管理》镜像库管理，添加相同代码镜像库时报错

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-BE-Platform-MGMT#14]
管理门户》镜像管理》镜像库管理，添加相同代码镜像库时报错，信息如下：
 12:00:40,002  INFO SimpleSsoUserLoginListener:21 -  sys-frame refresh login successful. 
  13:55:07,838 ERROR BinarySpringServlet:273 -  mvc process error! 
  com.binary.framework.exception.DubboException:  call remote service 'PcImageRepositorySvc.saveOrUpdate()' error!  is exists code 'NJ_IMG_TEAT01'! 
                at com.binary.framework.dubbo.rest.DubboRestClient.request(DubboRestClient.java:97)
                at com.binary.framework.dubbo.rest.impl.DubboRestClientHandler.doRemoteMethod(DubboRestClientHandler.java:74)
                at com.binary.framework.dubbo.rest.impl.DubboRestClientHandler.invoke(DubboRestClientHandler.java:46)
                at com.sun.proxy.$Proxy11.saveOrUpdate(Unknown Source)
                at com.aic.paas.console.res.peer.impl.PcImageRepositoryPeerImpl.saveOrUpdate(PcImageRepositoryPeerImpl.java:62)
                at com.aic.paas.console.res.mvc.PcImageRepositoryMvc.saveOrUpdate(PcImageRepositoryMvc.java:74)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:606)
                at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
                at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:436)
                at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:424)
                at com.binary.framework.spring.BinarySpringServlet.doDispatch(BinarySpringServlet.java:222)
                at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
                at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
                at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
                at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
                at com.binary.framework.web.filter.LoginValidateFilter.doFilter(LoginValidateFilter.java:216)
                at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
                at com.binary.framework.web.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:28)
                at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
                at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
                at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
                at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
                at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
                at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)

**Comment by chen-xm** [comment]
已修改

**Comment by chen-xm** [comment]
1）、提测的功能说明：数据中心、资源中心、网络区域、服务器信息添加、修改时，代码相同时，提交时报错。已修改为弹出提示框
	2）、代码分支说明：develop
	3）、配置信息说明：无
	4）、数据库说明：无
	5）、是否有特殊的第三方软件安装：无
