### ISSUE TITLE
【一般】管理门户》资源管理》机房信息添加/修改时，机房编号重复时，报错

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-BE-Platform-MGMT#4]
1. 管理门户》资源管理》机房信息添加、修改时，代码相同时，提交时报错
2. 数据中心、资源中心、网络区域、服务器信息添加、修改时也有此问题
报错信息如下：
2016-03-04 10:50:11  [ 11975273@qtp-1087161483-5:51788351 ] - [ ERROR ]   mvc process error! 
com.binary.framework.exception.DubboException:  call remote service 'PcCompRoomSvc.saveOrUpdate()' error!  is exists code 'room-22'! 
                at com.binary.framework.dubbo.rest.DubboRestClient.request(DubboRestClient.java:97)
                at com.binary.framework.dubbo.rest.impl.DubboRestClientHandler.doRemoteMethod(DubboRestClientHandler.java:74)
                at com.binary.framework.dubbo.rest.impl.DubboRestClientHandler.invoke(DubboRestClientHandler.java:46)
                at com.sun.proxy.$Proxy8.saveOrUpdate(Unknown Source)
                at com.aic.paas.console.res.peer.impl.PcCompRoomPeerImpl.saveOrUpdate(PcCompRoomPeerImpl.java:33)
                at com.aic.paas.console.res.mvc.PcCompRoomMvc.saveOrUpdate(PcCompRoomMvc.java:52)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:606)
                at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
                at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:436)
                at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:424)
                at com.binary.framework.spring.BinarySpringServlet.doDispatch(BinarySpringServlet.java:222)
                at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
                at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
                at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
                at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
                at com.binary.framework.web.filter.LoginValidateFilter.doFilter(LoginValidateFilter.java:216)

**Comment by wanwb** [comment]
已修改

**Comment by yuanhj3** [comment]
错误提示应该修改成 中文，如 “机房代码重复或已存在”

**Comment by chen-xm** [comment]
1）、提测的功能说明：数据中心、资源中心、网络区域、服务器信息添加、修改时，代码相同时，提交时报错。弹出提醒框
	2）、代码分支说明：develop
	3）、配置信息说明：无
	4）、数据库说明：无
	5）、是否有特殊的第三方软件安装：无
